export const SERVICE_NAMES = {
  AUTH: 'auth',
  USER: 'user',
  JOB: 'job',
  APPLICATION: 'application',
  EMAIL: 'email',
  CV_ANALYSIS: 'cvAnalysis',
} as const;

export const REST_SERVICES = [SERVICE_NAMES.AUTH, SERVICE_NAMES.CV_ANALYSIS] as const;

export const HTTP_TIMEOUTS = {
  DEFAULT: 5000,
  AUTH: 30000,
  CV_ANALYSIS: 30000,
} as const;

export const RETRY_CONFIG = {
  DEFAULT_MAX_RETRIES: 3,
  DEFAULT_RETRY_DELAY: 1000,
  AUTH_MAX_RETRIES: 0,
  CV_ANALYSIS_MAX_RETRIES: 2,
  CV_ANALYSIS_RETRY_DELAY: 2000,
} as const;

export const ENVIRONMENT_VARIABLES = {
  AUTH_SERVICE_URL: 'AUTH_SERVICE_URL',
  USER_SERVICE_URL: 'USER_SERVICE_URL',
  JOB_SERVICE_URL: 'JOB_SERVICE_URL',
  APPLICATION_SERVICE_URL: 'APPLICATION_SERVICE_URL',
  EMAIL_SERVICE_URL: 'EMAIL_SERVICE_URL',
  CV_ANALYSIS_SERVICE_URL: 'CV_ANALYSIS_SERVICE_URL',
} as const;
